---
name: build

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Build image
        run: docker build -q -t byrdal/j2cli:latest .
