---
name: build

on:
  pull_request:
    branches: ['**']
  push:
    branches: ['**']

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Build image
        run: docker build -q -t byrdal/j2cli:latest .
